apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx

# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  type: hello

resources:
- deployment.yaml
- service.yaml
- hpa.yaml